## Lecture : 1 
> ### Topic : Numpy Arrays

In [ ]:
import numpy as np

In [3]:
newList = [1,2,3,4]

In [4]:
np.array(newList)

array([1, 2, 3, 4])

In [5]:
newArr = np.array(newList)

In [6]:
type(newArr)

numpy.ndarray

In [7]:
Matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
np.array(Matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
#np.arange(<Starting point>, <Ending point>, <Stepvalue>) creates an array from scratch 
arangeArray = np.arange(0,12,3)

In [10]:
arangeArray

array([0, 3, 6, 9])

In [12]:
# Numpy comes with its own random module
#np.random.rand() returns a linear array of random integers from range [0,1) which means closed on 0 and open on 1 
np.random.rand(50)

array([0.7795546 , 0.22533266, 0.55847512, 0.73470466, 0.30156032,
       0.23438593, 0.06744383, 0.35949015, 0.52916662, 0.9723208 ,
       0.95098647, 0.64318176, 0.67585945, 0.9599073 , 0.99587054,
       0.24279403, 0.2082484 , 0.03348852, 0.30739302, 0.01047308,
       0.67811254, 0.64454595, 0.4278828 , 0.87024255, 0.14980779,
       0.23954607, 0.4449641 , 0.02912608, 0.5391902 , 0.33984415,
       0.06660993, 0.424592  , 0.25291563, 0.38848638, 0.20490707,
       0.26310304, 0.39494561, 0.31356502, 0.67182338, 0.68004675,
       0.13986499, 0.38115921, 0.11864477, 0.46819522, 0.42800412,
       0.43966535, 0.05208484, 0.19848344, 0.28689372, 0.48975769])

In [13]:
np.random.rand(5,6)

array([[0.31078872, 0.86662591, 0.18299053, 0.61897914, 0.09835332,
        0.41675013],
       [0.80336533, 0.46297291, 0.19359342, 0.71023301, 0.98914358,
        0.4145277 ],
       [0.6328614 , 0.56535223, 0.32622727, 0.98632582, 0.46061122,
        0.61384259],
       [0.10269638, 0.36746016, 0.39060861, 0.52819816, 0.7871609 ,
        0.98986204],
       [0.62548693, 0.25733216, 0.30495839, 0.6493505 , 0.16812148,
        0.18825365]])

In [2]:
import numpy as np

In [4]:
#The zeros() returns an array of floating point zeros
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
#The ones() is  very similar to zeros() it returns an array of floating point ones
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
# np.linspace(<Starting Point> , <Ending Point> ,<StepValue>)
#This Creates an array of evenly spaced numbers 
# End point is also included 
np.linspace(5,10,5)

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [7]:
'''Returns an Array in form of a Standard normal distribution
with mean value of zero and variance of 1 '''
np.random.randn(5,5)

array([[-0.06113308,  0.25396002, -0.00760264, -1.36606633, -1.34113167],
       [-0.48640953, -1.67419588,  0.9937407 ,  0.23481058,  0.43147843],
       [-0.14276547, -2.54701149, -1.41244382,  0.08166875, -0.99514346],
       [-1.27244638,  0.89979971,  0.97799826, -0.02475346, -0.26267673],
       [ 1.47049808,  0.57844118,  0.52911435,  2.23598585, -1.06788681]])

In [8]:
#Returns an array of random integers 
np.random.randint(2,40,(4,5))

array([[28, 23, 27, 38, 34],
       [14, 38, 31, 30,  4],
       [29, 23, 38, 16, 38],
       [12, 14, 15, 12, 13]])

In [10]:
#Remembers the random array created by rand function 
np.random.seed(1)
np.random.rand(5)

array([4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01,
       1.46755891e-01])

In [11]:
# The reshape() rearranges the matrix in a specific shape 
Arr = np.arange(0,25)
Arr.reshape(5,5) # <--- Shape 5 rows by 5 colmns 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [15]:
Arr = np.random.randint(0,2450, 4)
# The <Array_Name>.max()---> Returns the maximum numerical value element of the Array
print(Arr.max())
# The <Array_Name>.min()---> Returns the minimum numerical value element of the Array
print(Arr.min())
# The <Array_Name>.argmax()---> Returns the index of maximum numerical value element of the Array
print(Arr.argmax())
# The <Array_Name>.argmin()---> Returns the index of minimum numerical value element of the Array
print(Arr.argmin())

2189
1110
2
1


In [19]:
# Returns the Shape of the Array 
Arr.shape


(4,)

 ## Lecture : 2 
 > ### Topic : Indexing and Selection
 