In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from '/opt/anaconda3/lib/python3.9/site-packages/numpy/__init__.py'>

In [3]:
newList = [1,2,3,4]

In [4]:
np.array(newList)

array([1, 2, 3, 4])

In [5]:
newArr = np.array(newList)

In [6]:
type(newArr)

numpy.ndarray

In [7]:
Matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
np.array(Matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
arangeArray = np.arange(0,12,3)

In [10]:
arangeArray

array([0, 3, 6, 9])

In [12]:
np.random.rand(50)

array([0.7795546 , 0.22533266, 0.55847512, 0.73470466, 0.30156032,
       0.23438593, 0.06744383, 0.35949015, 0.52916662, 0.9723208 ,
       0.95098647, 0.64318176, 0.67585945, 0.9599073 , 0.99587054,
       0.24279403, 0.2082484 , 0.03348852, 0.30739302, 0.01047308,
       0.67811254, 0.64454595, 0.4278828 , 0.87024255, 0.14980779,
       0.23954607, 0.4449641 , 0.02912608, 0.5391902 , 0.33984415,
       0.06660993, 0.424592  , 0.25291563, 0.38848638, 0.20490707,
       0.26310304, 0.39494561, 0.31356502, 0.67182338, 0.68004675,
       0.13986499, 0.38115921, 0.11864477, 0.46819522, 0.42800412,
       0.43966535, 0.05208484, 0.19848344, 0.28689372, 0.48975769])

In [13]:
np.random.rand(5,6)

array([[0.31078872, 0.86662591, 0.18299053, 0.61897914, 0.09835332,
        0.41675013],
       [0.80336533, 0.46297291, 0.19359342, 0.71023301, 0.98914358,
        0.4145277 ],
       [0.6328614 , 0.56535223, 0.32622727, 0.98632582, 0.46061122,
        0.61384259],
       [0.10269638, 0.36746016, 0.39060861, 0.52819816, 0.7871609 ,
        0.98986204],
       [0.62548693, 0.25733216, 0.30495839, 0.6493505 , 0.16812148,
        0.18825365]])